/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import java.awt.Dimension;
import java.text.DecimalFormat;

/**
 *
 * @author UTFPR
 */
public class JanelaCircuito2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jnJanela2
     */
    public JanelaCircuito2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        resistor1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        potenciaresistor1 = new javax.swing.JTextField();
        resistor2 = new javax.swing.JTextField();
        potenciaresistor2 = new javax.swing.JTextField();
        modulofonte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        modofonte = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();

        setTitle("Circuito 2 - Resistores em paralelo");

        jLabel2.setText("Potência R1 (Watts) :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Clique em OK os resultados desse circuito.");

        jLabel3.setText("Valor R2 (Ohms):");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jLabel4.setText("Potência R2 (Ohms):");

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jLabel5.setText("Módulo da Fonte (módulo da fonte):");

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jLabel6.setText("Modo da Fonte (V ou A):");

        resistor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resistor1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/resistores2.jpg"))); // NOI18N

        potenciaresistor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaresistor1ActionPerformed(evt);
            }
        });

        resistor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resistor2ActionPerformed(evt);
            }
        });

        potenciaresistor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaresistor2ActionPerformed(evt);
            }
        });

        modulofonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulofonteActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor R1 (Ohms):");

        modofonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modofonteActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resistor1)
                                            .addComponent(potenciaresistor1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modulofonte)
                                            .addComponent(modofonte)
                                            .addComponent(potenciaresistor2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(resistor2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(207, 207, 207))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btSair)
                                        .addGap(104, 104, 104)
                                        .addComponent(btLimpar)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(82, 82, 82))
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(btOk))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(resistor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(potenciaresistor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(resistor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(potenciaresistor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(modulofonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modofonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btOk)
                    .addComponent(btSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        result.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if(resistor1.getText().isEmpty()||potenciaresistor1.getText().isEmpty()
            ||resistor2.getText().isEmpty()||potenciaresistor1.getText().isEmpty()
            ||modulofonte.getText().isEmpty()||modofonte.getText().isEmpty()||
            (Double.parseDouble(resistor1.getText())<= 0.0)||(Double.parseDouble(potenciaresistor1.getText())<= 0.0)
            ||(Double.parseDouble(resistor2.getText())<= 0.0)||(Double.parseDouble(potenciaresistor2.getText())<= 0.0)
            ||(Double.parseDouble(modulofonte.getText()) <= 0.0)){
            result.append("Há campo(s) vazio(s) ou campos de texto com valores negativos ou maior que 0.\n");
        }
        else{
            result.append("Atenção a entrada de dados!!!!\n");
            Circuito2 c2 = new Circuito2();
            DecimalFormat f = new DecimalFormat("####0.0000");
            c2.parametros(new Resistor(Double.parseDouble(potenciaresistor1.getText()),Double.parseDouble(resistor1.getText())),new Resistor(Double.parseDouble(potenciaresistor2.getText()),
                Double.parseDouble(resistor2.getText())),new Fonte(0.0,Double.parseDouble(modulofonte.getText())));
        if("V".equals(modofonte.getText())){
            result.append("\nResistência Equivalente: " + f.format(c2.equivalente()) + " Ohms\nCorrente Elétrica: " + f.format(c2.corrente()) + " A\nCorente R1:" + f.format(c2.corrente1()) +
                " A\nCorrente R2:" + f.format(c2.corrente2()) + " A\nPotência R1:" + f.format(c2.potencia1()) + " Watts\nPotência R2:" + f.format(c2.potencia2()) + "Watts");
        }
        else if("A".equals(modofonte.getText())){
            result.append("\nResistência Equivalente: " + f.format(c2.equivalente()) + " Ohms\nCorrente Elétrica: " + f.format(c2.getF().get(0).getValor()) + " A\nCorrente R1:" + f.format(c2.correnter1()) +
                " A\nCorrente R2:" + f.format(c2.correnter2()) + " A\nPotência R1:" + f.format(c2.potenciar1()) + " Watts\nPotência R2:" + f.format(c2.potenciar2()) + "Watts");
        }
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void resistor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resistor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resistor1ActionPerformed

    private void potenciaresistor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaresistor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaresistor1ActionPerformed

    private void resistor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resistor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resistor2ActionPerformed

    private void potenciaresistor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaresistor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaresistor2ActionPerformed

    private void modulofonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulofonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulofonteActionPerformed

    private void modofonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modofonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modofonteActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
    this.dispose();
    }//GEN-LAST:event_btSairActionPerformed
    public void setPosicao() {
      Dimension d = this.getDesktopPane().getSize();
      this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modofonte;
    private javax.swing.JTextField modulofonte;
    private javax.swing.JTextField potenciaresistor1;
    private javax.swing.JTextField potenciaresistor2;
    private javax.swing.JTextField resistor1;
    private javax.swing.JTextField resistor2;
    private javax.swing.JTextArea result;
    // End of variables declaration//GEN-END:variables
}
