package Final;

import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author UTFPR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaInterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu1 = new javax.swing.JMenu();
        jmJanela1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmJanela2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmJanela3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmJanela4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmJanela5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmJanela6 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmJanela7 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmJanela8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Circuitos");
        setResizable(false);

        janelaInterna.setBackground(new java.awt.Color(0, 102, 255));
        janelaInterna.setToolTipText("");
        janelaInterna.setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout janelaInternaLayout = new javax.swing.GroupLayout(janelaInterna);
        janelaInterna.setLayout(janelaInternaLayout);
        janelaInternaLayout.setHorizontalGroup(
            janelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        janelaInternaLayout.setVerticalGroup(
            janelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        mnMenu1.setText("Modelos");

        jmJanela1.setText("Circuito 1 - Resistores em série");
        jmJanela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela1ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela1);
        mnMenu1.add(jSeparator1);

        jmJanela2.setText("Circuito 2 - Resistores em paralelo");
        jmJanela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela2ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela2);
        mnMenu1.add(jSeparator2);

        jmJanela3.setText("Circuito 3 - Conversão estrela triângulo");
        jmJanela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela3ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela3);
        mnMenu1.add(jSeparator3);

        jmJanela4.setText("Circuito 4 - Conversao triângulo estrela");
        jmJanela4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela4ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela4);
        mnMenu1.add(jSeparator4);

        jmJanela5.setText("Circuito 5 - AmpOp Inversor ");
        jmJanela5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela5ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela5);
        mnMenu1.add(jSeparator5);

        jmJanela6.setText("Circuito 6 - AmpOp Não Inversor");
        jmJanela6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJanela6ActionPerformed(evt);
            }
        });
        mnMenu1.add(jmJanela6);
        mnMenu1.add(jSeparator6);

        jmJanela7.setText("Circuito 7 - AmpOp Somador Inversor");
        mnMenu1.add(jmJanela7);
        mnMenu1.add(jSeparator7);

        jmJanela8.setText("Circuito 8");
        mnMenu1.add(jmJanela8);

        jMenuBar1.add(mnMenu1);

        jMenu2.setText("Salvar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaInterna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmJanela6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela6ActionPerformed
    JanelaCircuito6 janelaCircuito6 = new JanelaCircuito6();
    janelaInterna.add(janelaCircuito6);
    janelaCircuito6.setPosicao();
    janelaCircuito6.setVisible(true);
    }//GEN-LAST:event_jmJanela6ActionPerformed

    private void jmJanela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela2ActionPerformed
    JanelaCircuito2 janelaCircuito2 = new JanelaCircuito2();
    janelaInterna.add(janelaCircuito2);
    janelaCircuito2.setPosicao();
    janelaCircuito2.setVisible(true);
    }//GEN-LAST:event_jmJanela2ActionPerformed

    private void jmJanela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela3ActionPerformed
    JanelaCircuito3 janelaCircuito3 = new JanelaCircuito3();
    janelaInterna.add(janelaCircuito3);
    janelaCircuito3.setPosicao();
    janelaCircuito3.setVisible(true);
    }//GEN-LAST:event_jmJanela3ActionPerformed

    private void jmJanela4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela4ActionPerformed
    JanelaCircuito4 janelaCircuito4 = new JanelaCircuito4();
    janelaInterna.add(janelaCircuito4);
    janelaCircuito4.setPosicao();
    janelaCircuito4.setVisible(true);
    }//GEN-LAST:event_jmJanela4ActionPerformed

    private void jmJanela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela1ActionPerformed
    JanelaCircuito1 janelaCircuito1 = new JanelaCircuito1();
    janelaInterna.add(janelaCircuito1);
    janelaCircuito1.setPosicao();
    janelaCircuito1.setVisible(true);
    }//GEN-LAST:event_jmJanela1ActionPerformed

    private void jmJanela5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJanela5ActionPerformed
    JanelaCircuito5 janelaCircuito5 = new JanelaCircuito5();
    janelaInterna.add(janelaCircuito5);
    janelaCircuito5.setPosicao();
    janelaCircuito5.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jmJanela5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JDesktopPane janelaInterna;
    private javax.swing.JMenuItem jmJanela1;
    private javax.swing.JMenuItem jmJanela2;
    private javax.swing.JMenuItem jmJanela3;
    private javax.swing.JMenuItem jmJanela4;
    private javax.swing.JMenuItem jmJanela5;
    private javax.swing.JMenuItem jmJanela6;
    private javax.swing.JMenuItem jmJanela7;
    private javax.swing.JMenuItem jmJanela8;
    private javax.swing.JMenu mnMenu1;
    // End of variables declaration//GEN-END:variables
}
